{"total_count":27,"runners":[{"id":132,"name":"1-core-ghsr6-qa","os":"Linux","status":"online","busy":false,"labels":[{"id":1
,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"}
,{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"
},{"id":7,"name":"el8","type":"custom"},{"id":17,"name":"qa","type":"custom"}]},{"id":133,"name":"2-core-ghsr6-qa","os":"Linu
x","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"r
ead-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","typ
e":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":17,"name":"qa","type":"custo
m"}]},{"id":134,"name":"3-core-ghsr6-qa","os":"Linux","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","
type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraf
orm","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8",
"type":"custom"},{"id":17,"name":"qa","type":"custom"}]},{"id":135,"name":"4-core-ghsr6-qa","os":"Linux","status":"online","b
usy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"nam
e":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"n
ame":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":17,"name":"qa","type":"custom"}]},{"id":136,"name":
"1-core-ghsr5-qa","os":"Linux","status":"offline","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"i
d":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},
{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id"
:17,"name":"qa","type":"custom"}]},{"id":137,"name":"2-core-ghsr5-qa","os":"Linux","status":"offline","busy":false,"labels":[
{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read
-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"
custom"},{"id":7,"name":"el8","type":"custom"},{"id":17,"name":"qa","type":"custom"}]},{"id":138,"name":"3-core-ghsr5-qa","os
":"Linux","status":"offline","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","
type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansib
le","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":17,"name":"qa","type
":"custom"}]},{"id":139,"name":"4-core-ghsr5-qa","os":"Linux","status":"offline","busy":false,"labels":[{"id":1,"name":"self-
hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name
":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"nam
e":"el8","type":"custom"},{"id":17,"name":"qa","type":"custom"}]},{"id":140,"name":"1-core-ghsr3-dev","os":"Linux","status":"
online","busy":true,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"i
d":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{
"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":15,"name":"dev","type":"custom"}]},{"id":1
41,"name":"2-core-ghsr3-dev","os":"Linux","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-
only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":
"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"cust
om"},{"id":15,"name":"dev","type":"custom"}]},{"id":142,"name":"3-core-ghsr3-dev","os":"Linux","status":"online","busy":false
,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","
type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel
8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":15,"name":"dev","type":"custom"}]},{"id":143,"name":"4-core-g
hsr3-dev","os":"Linux","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"nam
e":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"
name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":15,"name
":"dev","type":"custom"}]},{"id":144,"name":"1-core-ghsr4-dev","os":"Linux","status":"online","busy":true,"labels":[{"id":1,"
name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{
"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},
{"id":7,"name":"el8","type":"custom"},{"id":15,"name":"dev","type":"custom"}]},{"id":145,"name":"2-core-ghsr4-dev","os":"Linu
x","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"r
ead-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","typ
e":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":15,"name":"dev","type":"cust
om"}]},{"id":146,"name":"3-core-ghsr4-dev","os":"Linux","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted"
,"type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terr
aform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8
","type":"custom"},{"id":15,"name":"dev","type":"custom"}]},{"id":147,"name":"4-core-ghsr4-dev","os":"Linux","status":"online
","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,
"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":
6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":15,"name":"dev","type":"custom"}]},{"id":152,"n
ame":"1-core-ghsr3-prd","os":"Linux","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"
},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"cust
om"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},
{"id":22,"name":"prd","type":"custom"}]},{"id":153,"name":"2-core-ghsr3-prd","os":"Linux","status":"online","busy":false,"lab
els":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type"
:"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","t
ype":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":22,"name":"prd","type":"custom"}]},{"id":154,"name":"3-core-ghsr3-
prd","os":"Linux","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":2,"name":"L
inux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":4,"name":"terraform","type":"custom"},{"id":5,"name"
:"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id":7,"name":"el8","type":"custom"},{"id":22,"name":"pr
d","type":"custom"}]},{"id":155,"name":"4-core-ghsr3-prd","os":"Linux","status":"online","busy":false,"labels":[{"id":1,"name
":"self-hosted","type":"read-only"},{"id":2,"name":"Linux","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id"
:4,"name":"terraform","type":"custom"},{"id":5,"name":"ansible","type":"custom"},{"id":6,"name":"rhel8","type":"custom"},{"id
":7,"name":"el8","type":"custom"},{"id":22,"name":"prd","type":"custom"}]},{"id":166,"name":"devops-726","os":"Windows","stat
us":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":3,"name":"X64","type":"read-only"}
,{"id":15,"name":"dev","type":"custom"},{"id":23,"name":"Windows","type":"read-only"},{"id":26,"name":"devops","type":"custom
"},{"id":33,"name":"devops-726","type":"custom"}]},{"id":172,"name":"devops-824","os":"Windows","status":"online","busy":fals
e,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":23,"name":"Window
s","type":"read-only"},{"id":26,"name":"devops","type":"custom"},{"id":30,"name":"devops-824","type":"custom"}]},{"id":175,"n
ame":"devops-840","os":"Windows","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"
id":3,"name":"X64","type":"read-only"},{"id":23,"name":"Windows","type":"read-only"},{"id":26,"name":"devops","type":"custom"
},{"id":31,"name":"devops-840","type":"custom"}]},{"id":176,"name":"devops-841","os":"Windows","status":"online","busy":false
,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":23,"name":"Windows
","type":"read-only"},{"id":26,"name":"devops","type":"custom"},{"id":32,"name":"devops-841","type":"custom"}]},{"id":184,"na
me":"VDSREDTREEVOLE_CORPSYS_DEV","os":"Windows","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":
"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":15,"name":"dev","type":"custom"},{"id":23,"name":"Windows","type"
:"read-only"},{"id":97,"name":"deploy","type":"custom"}]},{"id":194,"name":"CQ-SM-V00916","os":"Windows","status":"online","b
usy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"},{"id":3,"name":"X64","type":"read-only"},{"id":17,"name
":"qa","type":"custom"},{"id":23,"name":"Windows","type":"read-only"},{"id":26,"name":"devops","type":"custom"}]},{"id":196,"
name":"CP-SM-V00915","os":"Windows","status":"online","busy":false,"labels":[{"id":1,"name":"self-hosted","type":"read-only"}
,{"id":3,"name":"X64","type":"read-only"},{"id":22,"name":"prd","type":"custom"},{"id":23,"name":"Windows","type":"read-only"
},{"id":26,"name":"devops","type":"custom"}]}]}
